version: '2'
services:
    pkaf-app:
        image: pkaf
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pkaf-postgresql:5432/pkaf
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pkaf-postgresql:
        extends:
            file: postgresql.yml
            service: pkaf-postgresql
